 language:
  node_js
node_js: 
  stable 
# assign build branches 
branches:
  only:
    – blog-source 
# cache this directory
cache:
  directories:
    – node_modules 
# S: Build Lifecycle 
before_install:
- openssl aes-256-cbc -K $encrypted_5fc59c827f08_key -iv $encrypted_5fc59c827f08_iv
  -in ./.travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "sundeji"
- git config --global user.email "Sundj_0825@163.com"

install:
- npm install hexo-cli -g
- npm install

script:
- hexo -version
- hexo clean
- hexo g
- hexo deploy
